//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBancoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credito()
        {
            this.TransaccionCredito = new HashSet<TransaccionCredito>();
        }
    
        public int IdCredito { get; set; }
        public long IdUsuario { get; set; }
        public int IdCuenta { get; set; }
        public bool Estado { get; set; }
        public decimal MontoCredito { get; set; }
        public decimal SaldoCredito { get; set; }
        public int IdMoneda { get; set; }
        public int PlazoMeses { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaccionCredito> TransaccionCredito { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
