//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBancoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int IdTarjeta { get; set; }
        public long IdUsuario { get; set; }
        public int IdCuenta { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public int PIN { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
